# First step: Check the versions

In [2]:
import torch
import numpy as np


In [3]:
print(torch.__version__)
print(np.__version__)
print("I'm ready!")

2.5.1
1.26.4
I'm ready!


# Basics in PyTorch I

- (Code) Tensor operations
    - Recap Linear Algebra: algebraic operations
    - Modifying the shape of a Tensor
- (Theory) The relation among (Dataset, DataLoader, Model, Loss)
    - (Code) How to prepare a dataset (with Pandas)

- (Theory) A Training Loop


## 1+2=3: How to represent scalars
- data types: int, float, double 
- (optional) how to read the documentation[link](https://docs.pytorch.org/docs/stable/tensors.html)


In [4]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
z = x + y
print(z.dtype)


torch.float32


## [1, 2]: vector and vector operations
- A vector is a list. A vector is a one-dimentional tensor? Or a two-dimeantional tensor?
- The **shape** of a tensor.
    - Row vector
    - Column vector
- Adding a vector to a scalar
- Adding a vector to a vector
    - row vector + row vector
    - row vector + col vector
    - col vector + col vector
    - col vector + row vector

### Representing a vector in List

In [5]:
# [1, 2] + 1 = [2, 3]
# in list 
x = [1, 2]

# a row vector 

# row vector's len [D]
print(x)
print(len(x))

# a row vector 
x = [
    [1, 2]
]
print('out', len(x))
print('in', len(x[0]))
# row vector's len [1, D]
# (2,)
# (1, 2)

[1, 2]
2
out 1
in 2


In [6]:
# a col vector?
col = [
    [1],
    [2]
]
# col vector len

In [7]:
print(len(col))
print(len(col[0]))

2
1


### Representing a vector: numpy

In [8]:
import numpy as np
# row vector [D]
row = np.array([1, 2])
print(row)
print(row.shape) # (2,)
# row vector [D]
row = np.array([[1, 2]])
print(row)
print(row.shape) # (2, 1)

# row vector shape

[1 2]
(2,)
[[1 2]]
(1, 2)


In [9]:
row = np.array([[1, 2, 3, 4]])
print(row.shape)

(1, 4)


In [10]:
# col vector [D, 1]
col = [
    [1],
    [2]
]
col_np = np.array(col)
# shape
print(col_np)
print(col_np.shape)


[[1]
 [2]]
(2, 1)


### Representing a vector: torch

In [11]:
# row [D]
row = [1, 2]
row_torch = torch.tensor(row)
print(row_torch)
print(row_torch.shape)

tensor([1, 2])
torch.Size([2])


In [12]:
row = [[1, 2, 34, 56]]
row_torch = torch.Tensor(row)
print(row_torch)
print(row_torch.shape)


tensor([[ 1.,  2., 34., 56.]])
torch.Size([1, 4])


In [13]:
# col [D, 1] and shape
col = [
    [1],
    [2],
    [342],
    [32]
]
col_torch = torch.tensor(col)
print(col_torch)
print(col_torch.shape)

tensor([[  1],
        [  2],
        [342],
        [ 32]])
torch.Size([4, 1])


### Vector operations in PyTorch

In [14]:
# x + scalar, - x /
#[1, 2] + 2 = [3, 4]
row = torch.tensor([1, 2])
out = row + 2
print(out)

tensor([3, 4])


In [15]:
# x + y, - x /
# [1, 2] + [3, 4] = [4, 6]
x = torch.tensor([[1, 2]]) # 1, n
y = torch.tensor([
    [3], 
    [4]]) # 1, n
out = x + y
print('x', x, x.shape)
print('y', y, y.shape)
print('out', out, out.shape)
# broadcasting
# [1, 2]
# [1, 2]

# 3  3
# 4  4

# 4, 5
# 5, 6

x tensor([[1, 2]]) torch.Size([1, 2])
y tensor([[3],
        [4]]) torch.Size([2, 1])
out tensor([[4, 5],
        [5, 6]]) torch.Size([2, 2])


## Matrix 

### Representation

In [16]:
# in list, a 2x3 matrix
# 4 5 10
# 5 6 20
mat = [
    [4, 5, 10],
    [5, 6, 20]
]
print('mat', mat)
# print len
print('out', len(mat))
print('in', len(mat[0]))

mat [[4, 5, 10], [5, 6, 20]]
out 2
in 3


In [17]:
# numpy a 2x3 matrix
# print shape
mat_np = np.array([
    [4, 5, 10],
    [5, 6, 20]
])
print(mat_np)
print(mat_np.shape)

[[ 4  5 10]
 [ 5  6 20]]
(2, 3)


In [18]:
# tensor
mat_torch = torch.tensor(
    [
        [4, 5, 10],
        [5, 6, 20]
    ]
)
print(mat_torch)
print(mat_torch.shape)

tensor([[ 4,  5, 10],
        [ 5,  6, 20]])
torch.Size([2, 3])


### Operations: Addition and Subtraction

In [19]:
# matrix + scalar
mat = torch.tensor([[1, 2], 
       [2, 3]])
print('mat', mat)
out = mat + 1
print('out', out)



mat tensor([[1, 2],
        [2, 3]])
out tensor([[2, 3],
        [3, 4]])


In [20]:
# matrix + vector? 
# broadcast (opt)
mat = torch.tensor([
    [2, 2],
    [3, 3]
])
vec = torch.tensor([[2, 2]])
print('mat', mat, mat.shape)
print('vec', vec, vec.shape)
# [2, 2]
# [2, 2]
print(mat - vec)

mat tensor([[2, 2],
        [3, 3]]) torch.Size([2, 2])
vec tensor([[2, 2]]) torch.Size([1, 2])
tensor([[0, 0],
        [1, 1]])


In [21]:
# matrix + matrix
mat1 = torch.tensor(
    [
        [1, 2],
        [4, 10]
    ]
)
mat2 = torch.tensor(
    [
        [1, 2],
        [2, 5]
    ]
)
print(mat1.shape)
print(mat2.shape)
print(mat1 - mat2)

torch.Size([2, 2])
torch.Size([2, 2])
tensor([[0, 0],
        [2, 5]])


### Operations: multiplication

In [22]:
# x*y [1, 2] * [2, 3]
# broadcast (opt)
# non-singleton dim (opt)

import torch
matx = torch.tensor(
    [
        [15, 25] # row vector or tensor
    ]
)
print('matx', matx, matx.shape)

maty = torch.tensor(
    [
        [1, 1, 1],  # row 1
        [2, 2, 2]   # row 2
    ]
)
print('maty', maty, maty.shape)

# torch.matmul()
z = torch.matmul(matx, maty)
# more complete broadcasting than @
print('z with matmul', z, z.shape)
out = matx @ maty
print('out', out, out.shape)
# What's the difference between * and @? Element-wise versus dot product multiplication
# / is element-wise division


matx tensor([[15, 25]]) torch.Size([1, 2])
maty tensor([[1, 1, 1],
        [2, 2, 2]]) torch.Size([2, 3])
z with matmul tensor([[65, 65, 65]]) torch.Size([1, 3])
out tensor([[65, 65, 65]]) torch.Size([1, 3])


In [23]:
# x@y
# [m, n] [n, k]
# [3, 2] [2, 1] => [3, 1]
mat = torch.tensor([
    [1, 2],
    [4, 4],
    [5, 5]
])
# [1, 2] * [1, 3]
# 1*1 + 2*3 = 7
vec = torch.tensor(
    [
        [1],
        [3]
    ]
)

out = mat @ vec
print(out.shape)
print(out)

torch.Size([3, 1])
tensor([[ 7],
        [16],
        [20]])


In [24]:
# x / y?
# non-singleton dim (opt)

In [25]:
# inverse of a matrix
# shape [3, 4]
# print shape
# A * A-1 = I
# yX-1 = WXX-1 --> Identify matrix because its the inverse so it looks like this yX-1 = WX
# W = y / x

x = torch.tensor(
    [
        [1, 2, 3, 4],
        [0, 1, 4, 5],
        [5, 6, 0, 7]
    ],
    dtype=torch.float32
)
print(x)
# y = WX
xTx = x.T@x
# X: 3x4
# XT: 4x3
# XTX: 3x3
print(xTx.inverse())
# Only square matrices have inverses
# yXT = WXXT --> yXT = W * (XXT)
# x + y = 3 and 2x - y = 1
# The solution is the inverse of the formula
idm = xTx @ xTx.inverse()
print(idm)

tensor([[1., 2., 3., 4.],
        [0., 1., 4., 5.],
        [5., 6., 0., 7.]])
tensor([[ 2138813.5000, -1696301.8750,   516264.2188,   -73750.8594],
        [-1696299.7500,  1345343.8750,  -409449.7812,    58490.7852],
        [  516265.7188,  -409451.4375,   124616.3906,   -17802.8535],
        [  -73752.6641,    58492.3516,   -17803.2344,     2544.2529]])
tensor([[ 3.1250,  3.5000,  0.0625,  0.0547],
        [ 4.5000,  4.7500, -1.0000,  0.1250],
        [ 0.0000,  2.5000,  1.2500,  0.0625],
        [ 3.0000,  5.5000, -0.5000,  1.1875]])


### Others

In [26]:
# identity matrix I

I = torch.eye(3)
print(I)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [27]:
# transpose
xT = x.T
print(xT)

tensor([[1., 0., 5.],
        [2., 1., 6.],
        [3., 4., 0.],
        [4., 5., 7.]])


## Indexing

In [28]:
# get one scalar

In [29]:
# get a sub matrix

# Practice: Ex1

In [30]:
alpha = 1 / 6
x = torch.tensor([
    [-2],
    [9],
    [3],
    [-4]
])
b = torch.tensor([
    [1],
    [1/2],
    [-1/2],
    [-2]
])

y = alpha * x + b
print(y)

# exercise 1.2
x = torch.tensor(
    [1, -2, -0.5, 3],
    dtype=torch.float32
)
y = torch.tensor(
    [-3, 7, 2, 2],
    dtype=torch.float32
)
z = torch.dot(x, y)
print(z)

x = torch.tensor(
    [1, 0, 0.5],
    dtype=torch.float32
)
y = torch.tensor(
    [1, 2, 8],
    dtype=torch.float32
)
z = x * y
print(z)

# Exercise 2
# 2.1



tensor([[ 0.6667],
        [ 2.0000],
        [ 0.0000],
        [-2.6667]])
tensor(-12.)
tensor([1., 0., 4.])


In [31]:
# lib fractions (opt)
from fractions import Fraction
y1 = Fraction(float(y[0])).limit_denominator()
print(y1)

1


# Documentation
Reading materials: [torch.Tensor](https://docs.pytorch.org/docs/stable/tensors.html)

"If you don't understand don't worry about it."

Pick the one you understand, then practice the code.
I'll expect at least five hours of practicing.